---
- name: AIOps Alert Correlation Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        # No authentication required for demo - add token in production

  rules:
    # ========================================================================
    # Rule 1: Process batch of correlated alerts (main use case)
    # ========================================================================
    - name: Process batch of correlated alerts
      condition: event.payload.alerts is defined
      action:
        run_workflow_template:
          name: "AIOps: EDA Alert Correlation Workflow"
          organization: "AIOps Demos"
          job_args:
            extra_vars:
              correlated_alerts: "{{ event.payload.alerts }}"
              correlation_id: "{{ event.payload.correlation_id | default('') }}"
              dependency_tag: "{{ event.payload.dependency_tag | default('') }}"

    # ========================================================================
    # Rule 2: Generic alert catch-all with logging
    # ========================================================================
    - name: Log unmatched alerts
      condition: event.payload is defined
      action:
        debug:
          msg: "Received alert event: {{ event.payload }}"

    # ========================================================================
    # Rule 3: Health check endpoint
    # ========================================================================
    - name: Health check response
      condition: event.payload.action is defined and event.payload.action == "health_check"
      action:
        debug:
          msg: "EDA rulebook is active and healthy"
